### ISSUE TITLE
Sonos config

### ISSUE THREAD

**Issue by xinQuon** [Psychokiller1888/SnipsSonosInvader#1]
Hi Psychokiller,
how can i add a library on every Sonos Player or do you mean to add a music library over the Sonos GUI? Do you have a how-to-link?

I plan to reimplement and extend your App for the german snips store :-)

**Comment by Psychokiller1888** [comment]
Hi!

You do know that under the MIT license I have applied to my repositories you should fork the repo and not just copy paste the code to your repositories, right?

By adding a library I mean over the Sono GUI, adding a music source location

**Comment by xinQuon** [comment]
Hi,
thanks. 

the licence:
I have delete the repository now an i will make a new repo and fork yours
...sorry i am new on githup and in this business - i have to read a little bit more about the laws.

**Comment by Psychokiller1888** [comment]
No problem mate. It's just common sense imo that you don't just rip off the original work and reupload on your account. Keep the original license and the link back and you're good to go!

**Comment by xinQuon** [comment]
you're right. I was a bit hasty...
